### ISSUE TITLE
pre-trained model weights

### ISSUE THREAD

**Issue by ktrapeznikov** [davide-coccomini/MINTIME-Multi-Identity-size-iNvariant-TIMEsformer-for-Video-Deepfake-Detection#1]
Hi,

Can you release pertained model weights?

Thanks

**Comment by davide-coccomini** [comment]
Hi, I updated the README with the pre-trained models. You can find MINTIME-XC at https://drive.google.com/drive/folders/1ti3U5jZULTgwx-sik9XjJDEB1_2hAsgi?usp=sharing

**Comment by ktrapeznikov** [comment]
Thanks. Which extractor model are the weights for? Xception or EfficientNet? I think they are for EfficientNet which outputs a different number of features (1024) while the model expects 2048.

```RuntimeError: mat1 and mat2 shapes cannot be multiplied (784x1280 and 2048x512)```

**Comment by davide-coccomini** [comment]
This is the XceptionNet, if you are using the inference code, remember to add the param:
--extractor_model 1

**Comment by ktrapeznikov** [comment]
Are you sure? So when I run with the following args:
```shell
python predict.py --video_path examples/fake_1_face_0.mp4 \
--model_weights weights/MINTIME_XC_Model_checkpoint30 \
--extractor_weights weights/MINTIME_XC_Extractor_checkpoint30 \
--extractor_model 1 \
--config config/size_invariant_timesformer.yaml
```
I get an error loading xception weights:
```
features_extractor = xception(num_classes=1, pretrain_path=opt.extractor_weights)
  File "/MINTIME-Multi-Identity-size-iNvariant-TIMEsformer-for-Video-Deepfake-Detection/models/xception.py", line 245, in xception
    state_dict = torch.load(pretrain_path)['state_dict']
KeyError: 'state_dict'
```

However, if I set `--extractor_model 0`. The extractor loads correctly but I get an error here which I think the model is expecting 2048 dim features from an xception extractor but I am loading efficientnet.
```
Original Traceback (most recent call last):
  File "lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "MINTIME-Multi-Identity-size-iNvariant-TIMEsformer-for-Video-Deepfake-Detection/models/size_invariant_timesformer.py", line 228, in forward
    tokens = self.to_patch_embedding(x)                                            # B x 8*7*7 x dim
  File "llib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (784x1280 and 2048x512)
```

**Comment by hellogeraldblah** [comment]
hello sorry, I am also testing out the program using the following arguments:

```python predict.py --video_path examples/fake_1_face_0.mp4 \
--model_weights weights/MINTIME_XC_Model_checkpoint30 \
--extractor_weights weights/MINTIME_XC_Extractor_checkpoint30 \
--extractor_model 0 \
--config config/size_invariant_timesformer.yaml```

and am encountering the same error:

```Traceback (most recent call last):
  File "predict.py", line 556, in <module>
    pred, identity_attentions, aggregated_attentions, identities, frames_per_identity = predict(opt.video_path, clustered_faces, config, opt)
  File "predict.py", line 406, in predict
    test_pred, attentions = model(features, mask=mask, size_embedding=size_embeddings, identities_mask=identities_mask, positions=positions)
  File "/home/cs14/anaconda3/envs/mintime/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cs14/anaconda3/envs/mintime/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/cs14/anaconda3/envs/mintime/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/d/MINTIME-Multi-Identity-size-iNvariant-TIMEsformer-for-Video-Deepfake-Detection/models/size_invariant_timesformer.py", line 228, in forward
    tokens = self.to_patch_embedding(x)                                            # B x 8*7*7 x dim
  File "/home/cs14/anaconda3/envs/mintime/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cs14/anaconda3/envs/mintime/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (784x1280 and 2048x512)```

following the fix of adding `state_dict = torch.load(pretrain_path)` fixes XceptionNet but how may I run the program with EfficientNet?

**Comment by ShengwuZheng** [comment]
Hi. When I use the pretrained model weights to predict my own video, I encountered an error.

I run this code below:
 python predict.py --video_path ./video/test.mp4 --model_weights ./model_weights/MINTIME_XC_Model_checkpoint30 --extractor_weights ./model_weights/MINTIME_XC_Extractor_checkpoint30 --config config/size_invariant_timesformer.yaml

And the error is :  IsADirectoryError: [Errno 21] Is a directory: './model_weights/MINTIME_XC_Extractor_checkpoint30'

In fact, the weights file is a directory( it is unzipped ).So what should I do?

Thanks for your help.
