### ISSUE TITLE
Questions about predict

### ISSUE THREAD

**Issue by zhang-zrq** [davide-coccomini/MINTIME-Multi-Identity-size-iNvariant-TIMEsformer-for-Video-Deepfake-Detection#4]

**Comment by zhang-zrq** [comment]
The command I entered is:
python3 predict.py --video_path ./examples/fake_2_faces_0_miss.mp4 --model_weights ../MINTIME_XC_Model_checkpoint30 --extractor_weights ../MINTIME_XC_Extractor_checkpoint30 --config config/size_invariant_timesformer.yaml

But the error message is as follows：
Traceback (most recent call last):
  File "predict.py", line 559, in <module>
    pred, identity_attentions, aggregated_attentions, identities, frames_per_identity = predict(opt.video_path, clustered_faces, config, opt)
  File "predict.py", line 409, in predict
    test_pred, attentions = model(features, mask=mask, size_embedding=size_embeddings, identities_mask=identities_mask, positions=positions)
  File "/root/miniconda3/envs/deepfakes/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/deepfakes/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/miniconda3/envs/deepfakes/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/MINTIME-Multi-Identity-size-iNvariant-TIMEsformer-for-Video-Deepfake-Detection-main/models/size_invariant_timesformer.py", line 228, in forward
    tokens = self.to_patch_embedding(x)                                            # B x 8*7*7 x dim
  File "/root/miniconda3/envs/deepfakes/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/deepfakes/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (784x1280 and 2048x512)

How can I modify this question？thank you

**Comment by gaurisharma360** [comment]
1. Change the number of channels in ./config/size_invariant_timesformer.yaml to 2048(XceptionNet). 
2. Also note that default value of extractor _model is set as 1
parser.add_argument('--extractor_model', type=int, default=1, 
                        help="Which model use for features extraction (0: EfficientNet; 1: XceptionNet).")

**Comment by yuntianlong2002** [comment]
Is the provided extractor model Xception based? After modified the params when I run: ```python3 predict.py --video_path ../datasets/ForgeryNet/raw/validation/Validation/video/val_video_release/test/1/3c46bbf1e66e7f04e8392bf824033edd/265bc223cea0d1ba71c5c5afbefc6a4b/video.mp4 --model_weights ./models/MINTIME/MINTIME_XC_Model_checkpoint30 --extractor_weights ./models/MINTIME/MINTIME_XC_Extractor_checkpoint30 --config config/size_invariant_timesformer.yaml --extractor_model 1``` I got ```Traceback (most recent call last):
  File "predict.py", line 555, in <module>
    pred, identity_attentions, aggregated_attentions, identities, frames_per_identity = predict(opt.video_path, clustered_faces, config, opt)
  File "predict.py", line 369, in predict
    features_extractor = xception(num_classes=1, pretrain_path=opt.extractor_weights)
  File "/home/ec2-user/SageMaker/MINTIME-Multi-Identity-size-iNvariant-TIMEsformer-for-Video-Deepfake-Detection/models/xception.py", line 245, in xception
    state_dict = torch.load(pretrain_path)['state_dict']
KeyError: 'state_dict'``` Any insights? Thanks in advance!

**Comment by davide-coccomini** [comment]
Hi, try to remove ['state_dict'] from line 245 of xception.py

**Comment by yuntianlong2002** [comment]
@davide-coccomini it worked! Thanks!

**Comment by CONQUERLYQ** [comment]
python3 predict.py --video_path ./examples/fake_1_face_0.mp4 --model_weights ./MINTIME_XC_Model_checkpoint30 --extractor_weights ./MINTIME_XC_Extractor_checkpoint30 --config config/size_invariant_timesformer.yaml

Traceback (most recent call last):
  File "predict.py", line 561, in <module>
    pred, identity_attentions, aggregated_attentions, identities, frames_per_identity = predict(opt.video_path, clustered_faces, config, opt)
  File "predict.py", line 373, in predict
    features_extractor = xception(num_classes=1, pretrain_path=opt.extractor_weights)
  File "/MINTIME-Multi-Identity-size-iNvariant-TIMEsformer-for-Video-Deepfake-Detection-main/models/xception.py", line 246, in xception
    state_dict = torch.load(pretrain_path)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
IsADirectoryError: [Errno 21] Is a directory: './MINTIME_XC_Extractor_checkpoint30'  
How can I modify this question？thank you
